# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'ShareThought' do
	use_frameworks!
	pod 'CocoaAsyncSocket', :inhibit_warnings => true
	pod 'MZFormSheetPresentationController'
end

target 'ShareThoughtTests' do

end

