# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'ShareThought' do
	use_frameworks!
	pod 'CocoaAsyncSocket', :inhibit_warnings => true
	pod 'MZFormSheetPresentationController'
	pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController', :branch => 'version_5.3.2_patch'
end

target 'ShareThoughtTests' do

end

