# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ShareThought' do
	use_frameworks!
	pod 'CocoaAsyncSocket', :inhibit_warnings => true
end

target 'ShareThoughtTests' do

end

